### ISSUE TITLE
ModuleNotFoundError: No module named 'exceptions'

### ISSUE THREAD

**Issue by Xewek** [hitblast/api.mcsrvstat.py#1]
```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\plg\wtyczka\minecraft.py", line 2, in <module>
    import mcsrvstat
  File "D:\pycham\wtyczka\lib\site-packages\mcsrvstat\__init__.py", line 1, in <module>
    from mcsrvstat.main import Base, Stats
  File "D:\pycham\wtyczka\lib\site-packages\mcsrvstat\main.py", line 7, in <module>
    from exceptions import NotBedrockError, InvalidServerTypeError
ModuleNotFoundError: No module named 'exceptions'
```

my cod

```
import mcsrvstat


staty = mcsrvstat.Stats(platform="java", ip_address="krystalmc.pl")

if staty.check_if_online():
    print("ok")
else:
    print("no")
```

**Comment by hitblast** [comment]
Thank you for your feedback! I guess I was being a little careless with the code and forgot to add `mcsrvstat.` before importing the modules in the **main.py** file.

The issue has been fixed in https://github.com/hitblast/api.mcsrvstat.py/releases/tag/0.0.0.4
